version: '3.8'
services:
  backend:
    container_name: python
    hostname: python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
        - .:/app
    networks:
      - api

  nginx:
    container_name: python-nginx-api
    hostname: python-nginx-api
    image: nginx
    restart: unless-stopped
    ports:
      - 8001:80
    # Прокидываем конфигурацию
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - api

# Контейнеры должны быть в одной сети, чтобы они могли обращаться друг к дургу по hostname, а не IP:PORT
networks:
  api:
    external:
      name: api
